# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormBerita',
            fields=[
                ('id_form_berita', models.AutoField(primary_key=True, serialize=False)),
                ('sumber', models.CharField(choices=[('WAGR', 'WAG Riau'), ('WAGJ', 'WAG Jambi'), ('WAGKALTENG', 'WAG Kalteng')], max_length=10)),
                ('kontak', models.CharField(max_length=15, null=True)),
                ('isi_berita', models.TextField()),
                ('jenis_kejadian', models.CharField(choices=[('WAGR', 'WAG Riau'), ('WAGJ', 'WAG Jambi'), ('WAGKALTENG', 'WAG Kalteng')], max_length=1)),
                ('waktu_kejadian', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageBerita',
            fields=[
                ('id_gambar', models.AutoField(primary_key=True, serialize=False)),
                ('gambar', models.ImageField(null=True, upload_to=b'')),
            ],
        ),
        migrations.AddField(
            model_name='formberita',
            name='gambar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.ImageBerita'),
        ),
    ]
