# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20170727_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beritamodel',
            name='jenis_kejadian',
            field=models.CharField(choices=[('F', 'Firespot'), ('H', 'Hotspot'), ('K', 'Karhutla')], max_length=1),
        ),
    ]
