# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20170727_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beritamodel',
            name='waktu_kejadian',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
