# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_auto_20170727_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageberitamodel',
            name='gambar',
            field=models.ImageField(null=True, upload_to='static/uploads/'),
        ),
    ]
